name: Check Docs

on: [push, pull_request, workflow_dispatch]

jobs:
  verify:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@1e204e9a9253d643386038d443f96446fa156a97 # v2
      - uses: actions/setup-dotnet@v1.8.2
        with:
          dotnet-version: "5.0.102"

      - name: Validate Code Snippets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet build /v:m -c Release tools/CodeFenceChecker/CodeFenceChecker.fsproj
          pwsh -Command ./check-code-snippets.ps1 -Exclude concepts/if-then-else-expressions,exercises/concept/cars-assemble
